color = #101010
verify-color = #00dd00
wrong-color = #dd0000
idle-color = #aaaaaa
circle-alpha = 0
# Supported values: default, win, none
pointer = win
time-format = %H:%M
date-format = %d.%m.%Y
unlock-indicator = true
ignore-empty-password = true
image=~/.config/lock.png
